apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: usdc-arbitrage-production

patches:
  - path: resources-patch.yaml

configMapGenerator:
  - name: usdc-arbitrage-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
