apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - hpa.yaml
  - ingress.yaml
  - pvc.yaml
  - service-mesh.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml

namespace: usdc-arbitrage
