apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usdc-arbitrage-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
