apiVersion: v1
kind: Secret
metadata:
  name: usdc-arbitrage-secrets
type: Opaque
stringData:
  SECRET_KEY: "replace_with_actual_secret_key"
  DB_PASSWORD: "strongpassword"
  DEFAULT_ADMIN_USERNAME: "admin"
  DEFAULT_ADMIN_EMAIL: "admin@example.com"
  DEFAULT_ADMIN_PASSWORD: "admin123!"
